version: '3.7'
services:
    mbdb:
        image: postgres:11
        networks:
            - net
        hostname: mbdb
        environment:
            - POSTGRES_PASSWORD=${PGPASSWORD}
    snekbox:
        image: pythondiscord/snekbox
        privileged: true
        init: true
        ipc: none
        hostname: snekbox
        networks:
            - net
    bot:
        build: .
        depends_on:
            - mbdb
            - snekbox
            - puller
        networks:
            - net
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
            - GOOGLE_API_KEY=${GOOGLE_API_KEY}
            - S3_BUCKET=${S3_BUCKET}
            - PGPASSWORD=${PGPASSWORD}
            - PGHOST=${PGHOST}
            - PGPORT=${PGPORT}
            - PGUSER=${PGUSER}
            - PGNAME=${PGNAME}
            - PYTHONUNBUFFERED=1
        healthcheck:
            test: ["CMD-SHELL", "discordhealthcheck"]
        volumes:
            - repo:/makubot
    puller:
        image: makusu2/pull_repo
        environment:
          REPO_URL: https://github.com/makusu2/makubot.git
        volumes:
            - repo:/repo

networks:
    net:

volumes:
  repo:
